Sb rb connect to firestore
the-collab-lab/tcl-42-smart-shopping-list pull request #17
Opened 2022-04-07 20:06 UTC by shirenekboyd

## Description

We installed `firebase` as a project dependency in our package.json file.  We added two new components, one for adding/sending data to the Cloud Firestore database with a `<button/>`, and another for getting/listening to data from Firestore and displaying it.  We are rendering these components (AddData.js, ShowData.js) in the App component.

## Related Issue

closes 1

## Acceptance Criteria

- [ ✓] `firebase` has been added as a project dependency
- [✓ ] Making a change in the Firestore database will update the data in the app
- [✓ ] Making a change in the app will update the data in Firestore

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|  ✓ | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|  ✓  | :link: Update dependencies |
|    | :scroll: Docs              |

### After

![Screen Shot 2022-04-07 at 3 01 21 PM](https://user-images.githubusercontent.com/89878197/162286519-0fe77c12-b35f-4c48-9ebc-dc1f5e4af07d.png)

## Testing Steps / QA Criteria

- Pull down the branch using `git pull origin sb-rb-connect-to-firestore`.
- `git checkout sb-rb-connect-to-firestore` to switch branches.
- `npm start` to open a local copy of the app.
- Click the button to add sample data to the Cloud Firestore database.

2022-04-07 22:07 UTC, timothy-taylor requested changes
Looks good! I left code comments inline for a couple minor syntax things around the map function in ShowData.  

One thought I had, and this might be excessive, but: I wonder whether we want to think about separating our backend logic from our frontend UI at this stage. The bulk of AddData and ShowData is really logic that could be made into custom hooks, like `useSnapshot` and `useAddDoc`, which could then be imported into our UI components as necessary.

for example, useSnapshot:
```
export const useSnapshot = () => { 
  const [docs, setDocs] = useState([]);

  useEffect(() => { 
    const unsubscribe = onSnapshot(collection(db, 'users'), (snapshot) => { 
      const snapshotDocs = [];
      snapshot.forEach((doc) => snapshotDocs.push(doc));
      setDocs(snapshotDocs);
    });
    return () => unsubscribe();
  }, []);

  return docs;
}
```

Since we (probably) won't need to use these logic hooks across multiple components this might not be necessary, so don't feel like you have to do this. I was just thinking about separation of concerns, and wanted to throw the idea out there in case it was interesting to anyone else.

2022-04-07 22:07 UTC, timothy-taylor commented on src/components/ShowData.js
> +          <ul>
we'll want to move `<ul>` outside of the map function here

2022-04-07 22:07 UTC, timothy-taylor commented on src/components/ShowData.js
> +            <li>{doc.id}</li>
as per [React docs](https://reactjs.org/docs/lists-and-keys.html), we'll want to add a key to list elements `<li key={doc.id}>`

2022-04-08 16:51 UTC, rjwbeard commented on src/components/ShowData.js
> +            <li>{doc.id}</li>
thanks for noticing that we missed this! I added a key attribute to our <li> items

2022-04-08 16:52 UTC, rjwbeard commented on src/components/ShowData.js
> +          <ul>
fixed it! another great catch

2022-04-08 17:00 UTC, rjwbeard commented
@timothy-taylor thank you for your thoughtful feedback! I've resolved the syntax errors locally on my machine and I'm wondering how to proceed in regards to file structure. I like your idea of separating the back end logic from our UI components and since we've established that our components are reading from and writing to Firestore, I can do that refactor now and remove the JSX from our components so they're ready for future use. I can rename the folder for these refactored files (useSnapshot and useAddDoc) to reflect that they're custom hooks.

2022-04-08 17:13 UTC, rjwbeard commented
I'm realizing now that I'm removing the JSX that I'm also deleting those syntax changes you suggested and that I just made. Nevertheless I thank you for catching them, it's still good practice to go back and make those edits!

2022-04-08 18:25 UTC, timothy-taylor requested changes, later dismissed
Looks good. Good call on the `hooks` directory. There is just one little missing argument in useAddDoc. 

It would be awesome to be able to test these hooks at some point. That is not trivial at all though, but could be a fun thing to read up on in our spare time.

2022-04-08 18:25 UTC, timothy-taylor commented on src/hooks/useAddDoc.js
> +export default function useAddDoc() {
We'll need to include the `itemName` variable used in line 12 as an argument to the function.

2022-04-22 00:24 UTC, closed without merging